Filesystem Updates

diff --git a/mainmenu b/mainmenu
--- a/mainmenu
+++ b/mainmenu
@@ -18,7 +18,7 @@ source ./variables.sh
 trap '' 2 
 
 read -p $cmdprompt input
-
+echo "$input" >> ./$usrname/history.txt
 case $input in
 
 	"LEARN")
@@ -69,6 +69,12 @@ case $input in
 		;&
 	"ESCALATE")
 		escalate
+		;&
+	"WHOAMI")
+		whoami
+		;&
+	"SCRAMBLE")
+		scramble
 		;&
 	"DISINTEGRATE")
 		exit 1
@@ -308,7 +314,7 @@ load-data()
 ##LOAD 
 aplay -q ./UI_Hacking_PasswordHelpAttempts.wav
 source ./filesystem.sh
-files=($maindir/*.txt)
+files=($usrname/*.txt)
 x=0
 echo "-------------------------------------------------" | pv -qL 90
 echo "NUMBER   |     Filename                          " | pv -qL 90
@@ -322,12 +328,22 @@ echo "-------------------------------------------------" | pv -qL 90
 echo
 read -p "Please Select " selection
 y=$((x+1))
+  if [[ $selection ]] && [ $selection -eq $selection 2>/dev/null ]
+  then
+     echo "Valid Selection"  | pv -qL 90
+	 echo
+  else
+     echo "INVALID INPUT"  | pv -qL 90
+	 echo
+	 prompt
+  fi
 
 if [ $selection -lt $x ]
 then
 	echo "Loading File"
 	echo "----------------------------------"  | pv -qL 90
 	echo
+	echo "${files[$selection]}" >> ./$usrname/history.txt
 	cat "${files[$selection]}" | pv -qL 90
 	echo
 	echo
@@ -341,6 +357,7 @@ then
 	echo "Incorrect Selection"
 fi
 
+
 	
 prompt
 }
@@ -351,7 +368,7 @@ image()
 ##LOAD IMAGE
 aplay -q ./UI_Hacking_PasswordHelpAttempts.wav
 source ./filesystem.sh
-files=($maindir/*.gif)
+files=($usrname/*.gif)
 x=0
 echo "-------------------------------------------------" | pv -qL 90
 echo "NUMBER   |     Filename                          " | pv -qL 90
@@ -366,12 +383,24 @@ echo
 read -p "Please Select " selection
 y=$((x+1))
 
+if [[ $selection ]] && [ $selection -eq $selection 2>/dev/null ]
+  then
+     echo "Valid Selection"  | pv -qL 90
+	 echo
+  else
+     echo "INVALID INPUT"  | pv -qL 90
+	 echo
+	 prompt
+  fi
+
 if [ $selection -lt $x ]
 then
 	echo "Loading File"
 	echo "----------------------------------"  | pv -qL 90
 	echo
+	echo "${files[$selection]}" >> ./$usrname/history.txt
 	catimg -w 120 -l 4 "${files[$selection]}"
+	echo
 	echo
 	echo
 fi
@@ -383,7 +412,6 @@ if [ $selection -gt $x ]
 then
 	echo "Incorrect Selection"
 fi
-
 	
 prompt
 }
@@ -595,6 +623,7 @@ escalate()
 ## ESCALATE Privs
 
 read -p "ENTER DESIRED USERNAME: " ninput
+echo "$ninput" >> ./$usrname/history.txt
 case $ninput in 
 			"root")
 				read -p "ENTER PASSWORD: " input
@@ -687,6 +716,44 @@ sleep 0.6
 
 }
 ##################################################################
+scramble()
+{
+if [ $root = "no" ]
+then 
+	echo "WARNING: YOU HAVE INSUFFICIENT COMPUTER PRIVILEGES TO ACCESS THIS FUNCTION."| pv -qL 90
+	sleep 2
+	echo "ACCESS ATTEMPT HAS BEEN LOGGED AND WILL BE REPORTED TO YOUR MANAGER." | pv -qL 90
+	prompt
+fi
+echo "WARNING: SCRAMBLE OF COMPUTER CORE HAS SERIOUS REPERCUSSIONS AND VOIDS YOUR WARRANTY"
+input "Confirm by typing SCRAMBLE:  input
+
+case 				
+					
+					
+#					"DISINTEGRATE")
+#						exit 1
+#						;&
+#					*)
+#						echo -e "INCORRECT PASSWORD" | pv -qL 90
+#						sleep 2
+#						aplay -q ./ui_hacking_passbad.wav  
+#						prompt
+#						;;
+}
+
+whoami()
+{
+echo "-------------------------------------------------"
+echo "Username: $usrname"
+echo "-------------------------------------------------"
+echo "Root status: $root"
+echo
+echo
+
+prompt
+
+}
 mainmenu
 
 
